/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Intel
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private ImageIcon imagemBotaoSinglePlayer;
    private ImageIcon imagemBotaoMultiPlayer;
    private ImageIcon imagemBotaoSair;
    private ImageIcon imagemLabelTitulo;
    public Menu() {
        initComponents(); 
        imagemBotaoSinglePlayer = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/botoes/botao_single_player.png"))
            .getImage()
            .getScaledInstance(256, 79, java.awt.Image.SCALE_SMOOTH)
    );imagemBotaoMultiPlayer = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/botoes/botao_multi_player.png"))
            .getImage()
            .getScaledInstance(256, 79, java.awt.Image.SCALE_SMOOTH)
    );imagemBotaoSair = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/botoes/botao_sair.png"))
            .getImage()
            .getScaledInstance(256, 79, java.awt.Image.SCALE_SMOOTH)
    );imagemLabelTitulo = new ImageIcon(new ImageIcon(getClass().getResource("/imagens/labels/label_pacman.png"))
            .getImage()
            .getScaledInstance(637, 177, java.awt.Image.SCALE_SMOOTH)
    );
        botaoPlayerSoloBT.setIcon(imagemBotaoSinglePlayer);
        botaoMultiPlayerBT.setIcon(imagemBotaoMultiPlayer);
        botaoSairBT.setIcon(imagemBotaoSair);
        labelTitulo.setIcon(imagemLabelTitulo);
        painelPrincipal.setBackground(new Color(22, 29, 36));
        painelPrincipal.setOpaque(true);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botaoPlayerSoloBT = new javax.swing.JButton();
        botaoSairBT = new javax.swing.JButton();
        botaoMultiPlayerBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelTitulo.setMaximumSize(new java.awt.Dimension(637, 177));
        labelTitulo.setMinimumSize(new java.awt.Dimension(637, 177));

        botaoPlayerSoloBT.setBorderPainted(false);
        botaoPlayerSoloBT.setContentAreaFilled(false);
        botaoPlayerSoloBT.setFocusPainted(false);
        botaoPlayerSoloBT.setMaximumSize(new java.awt.Dimension(256, 79));
        botaoPlayerSoloBT.setMinimumSize(new java.awt.Dimension(256, 79));
        botaoPlayerSoloBT.setPreferredSize(new java.awt.Dimension(256, 79));
        botaoPlayerSoloBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlayerSoloBTActionPerformed(evt);
            }
        });

        botaoSairBT.setBorderPainted(false);
        botaoSairBT.setContentAreaFilled(false);
        botaoSairBT.setFocusPainted(false);
        botaoSairBT.setMaximumSize(new java.awt.Dimension(256, 79));
        botaoSairBT.setMinimumSize(new java.awt.Dimension(256, 79));
        botaoSairBT.setPreferredSize(new java.awt.Dimension(256, 79));

        botaoMultiPlayerBT.setBorderPainted(false);
        botaoMultiPlayerBT.setContentAreaFilled(false);
        botaoMultiPlayerBT.setFocusPainted(false);
        botaoMultiPlayerBT.setMaximumSize(new java.awt.Dimension(256, 79));
        botaoMultiPlayerBT.setMinimumSize(new java.awt.Dimension(256, 79));
        botaoMultiPlayerBT.setPreferredSize(new java.awt.Dimension(256, 79));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMultiPlayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPlayerSoloBT, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(botaoPlayerSoloBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMultiPlayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPlayerSoloBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlayerSoloBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPlayerSoloBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMultiPlayerBT;
    private javax.swing.JButton botaoPlayerSoloBT;
    private javax.swing.JButton botaoSairBT;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
