/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package multiplayer.panels;

import main.Main;
import multiplayer.cliente.Cliente;
import multiplayer.cliente.ClienteSocket;
import multiplayer.panels.lobby.Lobby;
import multiplayer.panels.lobby.LobbyPanel;
import multiplayer.server.Server;

import javax.swing.*;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;

/**
 *
 * @author klaus
 */
public class FormMultiplayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormMultiplayerPanel
     */
    public FormMultiplayerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrarSalaBT = new javax.swing.JButton();
        criarSalaBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ipTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        portaTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(22, 29, 36));

        entrarSalaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/entrar sessões/botao_entrar_sala.png"))); // NOI18N
        entrarSalaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarSalaBTActionPerformed(evt);
            }
        });

        criarSalaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/entrar sessões/botao_criar_sala.png"))); // NOI18N
        criarSalaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarSalaBTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 104, 208));
        jLabel1.setText("Digite o IP (números e pontos):");

        ipTF.setBackground(new java.awt.Color(22, 29, 36));
        ipTF.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        ipTF.setForeground(new java.awt.Color(17, 104, 208));
        ipTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 104, 208), 5));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 104, 208));
        jLabel2.setText("Digite o número da porta:");

        portaTF.setBackground(new java.awt.Color(22, 29, 36));
        portaTF.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        portaTF.setForeground(new java.awt.Color(17, 104, 208));
        portaTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 104, 208), 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipTF)
                    .addComponent(portaTF)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entrarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(criarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entrarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrarSalaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarSalaBTActionPerformed
        try {
            String ipString = ipTF.getText().trim();
            InetAddress ip = InetAddress.getByName(ipString);
            int porta = Integer.parseInt(portaTF.getText().trim());

            if(ipString.isEmpty() || portaTF.getText().isEmpty()) {
                throw new IOException("Porta ou IP vazios.");
            }

            try(Socket socket = new Socket(ip, porta)) {

            }
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(this, "IP inválido, verifique se digitou corretamente com números e símbolos.",
                    "Problemas de conectar no servidor", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Porta deve ser um número inteiro", "Falha na porta", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "IP inválido ou porta inválida, verifique se digitou corretamente com números e símbolos.",
                    "Problemas ao conectar no servidor: " + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarSalaBTActionPerformed

    private void criarSalaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarSalaBTActionPerformed
        new Thread(() -> {
            try {
                Main.criarSala();
                Server.getInstance().setLobby(true);
                Lobby lobby = new Lobby();
                InetAddress ip = Server.getInstance().getServerSocket().getInetAddress();
                int porta = Server.getInstance().getPort();
                lobby.setClienteSocket(new ClienteSocket(ip, porta));
                lobby.getClienteSocket().enviar(new Cliente());
                lobby.setMeuPersonagem(lobby.escolherPersonagem());
                lobby.start();
            } catch (IOException e) {
                e.printStackTrace();
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Erro ao criar sala: " + e.getMessage());
                });
            }
        }).start();
    }//GEN-LAST:event_criarSalaBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarSalaBT;
    private javax.swing.JButton entrarSalaBT;
    private javax.swing.JTextField ipTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField portaTF;
    // End of variables declaration//GEN-END:variables
}
