/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package multiplayer.panels;

import itens.Item;
import main.Main;
import mapa.Tile;
import multiplayer.MultiplayerGame;
import multiplayer.cliente.Cliente;
import multiplayer.cliente.ClienteSocket;
import multiplayer.network.Response;
import multiplayer.panels.lobby.Lobby;
import multiplayer.server.Server;
import personagem.Personagem;
import personagem.fantasma.Fantasma;
import personagem.pacman.Pacman;

import javax.swing.*;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author klaus
 */
public class FormMultiplayerPanel extends javax.swing.JPanel {
    private GerenciadorMultiplayer gerenciador;

    /**
     * Creates new form FormMultiplayerPanel
     */
    public FormMultiplayerPanel() {
        try {
            initComponents();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            gerenciador = new GerenciadorMultiplayer();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrarSalaBT = new javax.swing.JButton();
        criarSalaBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ipTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        portaTF = new javax.swing.JTextField();
        nomeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 29, 36));

        entrarSalaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/entrar sessões/botao_entrar_sala.png"))); // NOI18N
        entrarSalaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarSalaBTActionPerformed(evt);
            }
        });

        criarSalaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/entrar sessões/botao_criar_sala.png"))); // NOI18N
        criarSalaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarSalaBTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 104, 208));
        jLabel1.setText("Digite o IP (números e pontos) para entrar na sala:");

        ipTF.setBackground(new java.awt.Color(22, 29, 36));
        ipTF.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        ipTF.setForeground(new java.awt.Color(17, 104, 208));
        ipTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 104, 208), 5));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 104, 208));
        jLabel2.setText("Digite o número da porta para entrar na sala:");

        portaTF.setBackground(new java.awt.Color(22, 29, 36));
        portaTF.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        portaTF.setForeground(new java.awt.Color(17, 104, 208));
        portaTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 104, 208), 5));

        nomeTF.setBackground(new java.awt.Color(22, 29, 36));
        nomeTF.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        nomeTF.setForeground(new java.awt.Color(17, 104, 208));
        nomeTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 104, 208), 5));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 104, 208));
        jLabel3.setText("Digite o nome de usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(ipTF).addComponent(portaTF).addComponent(nomeTF).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1).addComponent(jLabel2).addGroup(layout.createSequentialGroup().addComponent(entrarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(criarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jLabel3)).addGap(0, 0, Short.MAX_VALUE))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(ipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(portaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(entrarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(criarSalaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(129, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void entrarSalaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarSalaBTActionPerformed
        try {
            String ipString = ipTF.getText().trim();
            InetAddress ip = InetAddress.getByName(ipString);
            int porta = Integer.parseInt(portaTF.getText().trim());

            String nomeUsuario = verificarUsuario();

            if (ipString.isEmpty() || portaTF.getText().isEmpty()) {
                throw new IOException("Porta vazia ou IP vazio.");
            }

            gerenciador.entrarSala(nomeUsuario, ip, porta);
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(this, "IP inválido, verifique se digitou corretamente com números e símbolos.", "Problemas de conectar no servidor", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Porta deve ser um número inteiro", "Falha na porta", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "IP inválido ou porta inválida, verifique se digitou corretamente com números e símbolos.", "Problemas ao conectar no servidor: " + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarSalaBTActionPerformed

    private void criarSalaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarSalaBTActionPerformed
        try {
            String nomeUsuario = verificarUsuario();

            gerenciador.criarSala(nomeUsuario);
        } catch (IOException e) {
            SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Erro ao criar sala: " + e.getMessage()));
        }
    }//GEN-LAST:event_criarSalaBTActionPerformed

    private String verificarUsuario() throws IOException {
        String nomeUsuario = nomeTF.getText().trim();
        if (nomeUsuario.isEmpty()) {
            throw new IOException("Nome de usuário vazio.");
        }
        return nomeUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarSalaBT;
    private javax.swing.JButton entrarSalaBT;
    private javax.swing.JTextField ipTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JTextField portaTF;
    // End of variables declaration//GEN-END:variables
}
