/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase;

import mapa.imagens.ImagensTile;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import main.Main;

/**
 *
 * @author klaus
 */
public class ControlesPanel extends javax.swing.JPanel {

    private BufferedImage imagemAtual;
    private BufferedImage imgPadrao;
    private BufferedImage imgDireita;
    private BufferedImage imgEsquerda;
    private BufferedImage imgCima;
    private BufferedImage imgBaixo;
    private BufferedImage imgEsc;
    private BufferedImage imgF;
    private BufferedImage fundo;
    private boolean isImagensCarregadas;

    public ControlesPanel() {
        initComponents();
        setFocusable(true);
        requestFocusInWindow();
        isImagensCarregadas = false;
        new ImagensTile();
        fundo = ImagensTile.aberto;
    }

    public void carregarImagens() {
        try {
            imgPadrao = ImageIO.read(getClass().getResourceAsStream("/imagens/controles/controles.png"));
            imgDireita = ImageIO.read(getClass().getResourceAsStream("/imagens/controles/controles-direita.png"));
            imgEsquerda = ImageIO.read(getClass().getResourceAsStream(("/imagens/controles/controles-esquerda.png")));
            imgCima = ImageIO.read(getClass().getResourceAsStream("/imagens/controles/controles-cima.png"));
            imgBaixo = ImageIO.read(getClass().getResourceAsStream("/imagens/controles/controles-baixo.png"));
            imgEsc = ImageIO.read(getClass().getResourceAsStream(("/imagens/controles/controles-esc.png")));
            imgF = ImageIO.read(getClass().getResourceAsStream("/imagens/controles/controles-f.png"));
            imagemAtual = imgPadrao;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBT = new javax.swing.JButton();

        setForeground(new java.awt.Color(22, 29, 36));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        menuBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_menu .png"))); // NOI18N
        menuBT.setMaximumSize(new java.awt.Dimension(297, 86));
        menuBT.setMinimumSize(new java.awt.Dimension(292, 91));
        menuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_W) {
            imagemAtual = imgCima;
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_S) {
            imagemAtual = imgBaixo;
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_A) {
            imagemAtual = imgEsquerda;
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_D) {
            imagemAtual = imgDireita;
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            imagemAtual = imgEsc;
        } else if (evt.getKeyCode() == KeyEvent.VK_F) {
            imagemAtual = imgF;
        } else {
            imagemAtual = imgPadrao;
        }
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void menuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBTActionPerformed
        Main.configurarPanel(new MenuPanel());
    }//GEN-LAST:event_menuBTActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        super.paintComponent(g2d);

        g2d.drawImage(fundo, 0, 0, this.getWidth(), this.getHeight(), this);

        if (!isImagensCarregadas) {
            carregarImagens();
            isImagensCarregadas = true;
            imagemAtual = imgPadrao;
        }

        if (imagemAtual == null) return;

        int imgWidth = imagemAtual.getWidth();
        int imgHeight = imagemAtual.getHeight();

        int panelWidth = getWidth();
        int panelHeight = getHeight();

        double escala = Math.min(
                (double) panelWidth / imgWidth,
                (double) panelHeight / imgHeight
        ) - 0.01;

        int novoW = (int) (imgWidth * escala);
        int novoH = (int) (imgHeight * escala);

        int x = (panelWidth - novoW) / 2 + 150;
        int y = (panelHeight - novoH) / 2;

        g2d.drawImage(imagemAtual, x, y, novoW, novoH, this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menuBT;
    // End of variables declaration//GEN-END:variables
}
