/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fase;

import main.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Intel
 */
public class FaseJF extends javax.swing.JFrame {

    private boolean isFullScreen = false;

    /**
     * Creates new form Fase
     */
    public FaseJF() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                System.exit(0);
            }
        });
        bindKey("ESCAPE", () -> setFullScreen(false));
        bindKey("F", () -> setFullScreen(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE && isFullScreen) {
            setFullScreen(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_F && isFullScreen) {
            setFullScreen(true);
        }
    }//GEN-LAST:event_formKeyPressed

    public void setFullScreen(boolean fullScreen) {

        if (this.isFullScreen == fullScreen) {
            return; // já está no estado desejado → não faça nada
        }

        this.isFullScreen = fullScreen;

        GraphicsDevice gd = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getDefaultScreenDevice();

        this.setVisible(false);
        this.dispose();
        this.setUndecorated(fullScreen);

        try {
            if (fullScreen) {
                if (gd.isFullScreenSupported()) {
                    gd.setFullScreenWindow(this);
                } else {
                    gd.setFullScreenWindow(null);
                    this.setExtendedState(JFrame.NORMAL);
                    this.setLocationRelativeTo(null);
                }
            } else {
                gd.setFullScreenWindow(null);
                this.setExtendedState(JFrame.NORMAL);
                this.setLocationRelativeTo(null);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.setVisible(true);
    }

    private void bindKey(String key, Runnable action) {
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke(key), key);

        getRootPane().getActionMap().put(key, new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                action.run();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
