/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase;

import main.Direcao;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.List;

import mapa.Mapa;
import personagem.Personagem;
import personagem.fantasma.Fantasma;
import personagem.pacman.Pacman;

/**
 *
 * @author klaus
 */
public class FasePanel extends javax.swing.JPanel {

    protected Mapa mapa;
    protected List<Fantasma> fantasmas;
    protected Pacman pacman;
    protected Personagem personagem;

    public FasePanel(Mapa mapa, List<Fantasma> fantasmas, Pacman pacman) {
        initComponents();
        this.mapa = mapa;
        this.fantasmas = fantasmas;
        this.pacman = pacman;
        this.personagem = pacman;
        setFocusable(true);
        requestFocusInWindow();
    }

    public FasePanel(Mapa mapa, List<Fantasma> fantasmas, Pacman pacman, Personagem personagem) {
        initComponents();
        this.mapa = mapa;
        this.fantasmas = fantasmas;
        this.pacman = pacman;
        this.personagem = personagem;
        setFocusable(true);
        requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setForeground(new java.awt.Color(22, 29, 36));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_W) {
            personagem.setDirecao(Direcao.CIMA);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_S) {
            personagem.setDirecao(Direcao.BAIXO);
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_A) {
            personagem.setDirecao(Direcao.ESQUERDA);
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_D) {
            personagem.setDirecao(Direcao.DIREITA);
        }
    }//GEN-LAST:event_formKeyPressed

    @Override
    protected void paintComponent(Graphics g) {
        System.out.println("Paint component");
        Graphics2D g2d = (Graphics2D) g;
        super.paintComponent(g2d);

        int tileSize = Math.min(this.getWidth() / mapa.getMapa()[0].length, this.getHeight() / mapa.getMapa().length);
        tileSize = tileSize > 40 ? 38 : tileSize;
        mapa.draw(g2d, tileSize);

        for (Fantasma fantasma : fantasmas) {
            fantasma.draw(g2d, tileSize, mapa);
        }
        if(pacman != null) {
            pacman.draw(g2d, tileSize, mapa);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
