/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author klaus
 */
public class GameEndPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameEndPanel
     */
    public GameEndPanel() {
        initComponents();
        setOpaque(false);
        botoesPN.setBackground(new Color(0, 0, 0, 0));
        botoesPN.setForeground(new Color(0, 0, 0, 0));

        removerBordaBotoes();
    }

    private void removerBordaBotoes() {
        reiniciarBT1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        reiniciarBT1.setFocusPainted(false);
        reiniciarBT1.setContentAreaFilled(false);

        menuBT.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        menuBT.setFocusPainted(false);
        menuBT.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOverLB = new javax.swing.JLabel();
        botoesPN = new javax.swing.JPanel();
        reiniciarBT1 = new javax.swing.JButton();
        menuBT = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 51));

        gameOverLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameOverLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/labels/label_game_over.png"))); // NOI18N

        botoesPN.setBackground(new java.awt.Color(0, 0, 0));

        reiniciarBT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_reinicar.png"))); // NOI18N
        botoesPN.add(reiniciarBT1);

        menuBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_menu_grande.png"))); // NOI18N
        botoesPN.add(menuBT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameOverLB, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(botoesPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(gameOverLB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(botoesPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents
@Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setColor(new Color(0, 0, 51, 150));
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPN;
    private javax.swing.JLabel gameOverLB;
    private javax.swing.JButton menuBT;
    private javax.swing.JButton reiniciarBT1;
    // End of variables declaration//GEN-END:variables
}
