/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase;

import main.Main;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;

/**
 *
 * @author klaus
 */
public class MenuPanel extends javax.swing.JPanel {
    private BufferedImage imagemArcade;

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        try {
            imagemArcade = ImageIO.read(getClass().getResourceAsStream("/imagens/labels/pacmano.png"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairBT = new javax.swing.JButton();
        multiplayerBT = new javax.swing.JButton();
        controlesBT = new javax.swing.JButton();
        singleplayerBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 29, 36));

        sairBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_sair.png"))); // NOI18N
        sairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTActionPerformed(evt);
            }
        });

        multiplayerBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_multi_player.png"))); // NOI18N
        multiplayerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplayerBTActionPerformed(evt);
            }
        });

        controlesBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_controles.png"))); // NOI18N
        controlesBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlesBTActionPerformed(evt);
            }
        });

        singleplayerBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/botao_single_player.png"))); // NOI18N
        singleplayerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleplayerBTActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/labels/label_pacman.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlesBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singleplayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(singleplayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlesBT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiplayerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairBTActionPerformed

    private void singleplayerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleplayerBTActionPerformed
        Main.singlePlayer();
    }//GEN-LAST:event_singleplayerBTActionPerformed

    private void multiplayerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplayerBTActionPerformed
    }//GEN-LAST:event_multiplayerBTActionPerformed

    private void controlesBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlesBTActionPerformed
        Main.configurarPanel(new ControlesPanel());
    }//GEN-LAST:event_controlesBTActionPerformed

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();

        double proporcao = (double) getHeight() / imagemArcade.getHeight();
        int tamanhoWidth = (int) (imagemArcade.getWidth() * proporcao);

        g2d.drawImage(imagemArcade, getWidth() - tamanhoWidth, 0, tamanhoWidth, getHeight(), this);


        g2d.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton controlesBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multiplayerBT;
    private javax.swing.JButton sairBT;
    private javax.swing.JButton singleplayerBT;
    // End of variables declaration//GEN-END:variables
}
