/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase;

import singleplayer.Game;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.HashMap;

/**
 *
 * @author klaus
 */
public class SeletorFases extends javax.swing.JPanel {

    private final Game game;

    public SeletorFases(Game game) throws IOException {
        initComponents();
        carregarMapas();
        this.game = game;
        painelFases.setLayout(new FlowLayout(FlowLayout.LEFT));
    }

    public void carregarMapas() throws IOException {
        HashMap<ImageIcon, String> mapas = new HashMap<>();
        mapas.put(new ImageIcon(getClass().getResource("/mapas/imagens/mapa.png")), "/mapas/mapa.txt");
        mapas.put(new ImageIcon(getClass().getResource("/mapas/imagens/mapa1.png")), "/mapas/mapa1.txt");
        mapas.put(new ImageIcon(getClass().getResource("/mapas/imagens/mapa2.png")), "/mapas/mapa2.txt");
        mapas.put(new ImageIcon(getClass().getResource("/mapas/imagens/google.png")), "/mapas/google.txt");

        for (ImageIcon image : mapas.keySet()) {
            JButton mapaBT = new JButton(redimensionarImagem(image, image.getIconWidth() / 4, image.getIconHeight() / 4));
            mapaBT.setPreferredSize(new Dimension(image.getIconWidth() / 4, image.getIconHeight() / 4));
            painelFases.add(mapaBT);

            mapaBT.addActionListener(e -> game.selecionarFase(mapas.get(image)));
        }
    }

    private ImageIcon redimensionarImagem(ImageIcon imagem, int largura, int altura) {
        double escalaLargura = (double) largura / imagem.getIconWidth();
        double escalaAltura = (double) altura / imagem.getIconHeight();
        double escala = Math.min(escalaLargura, escalaAltura);

        int novaLargura = (int) (imagem.getIconWidth() * escala);
        int novaAltura = (int) (imagem.getIconHeight() * escala);
        Image imagemRedimensionada = imagem.getImage().getScaledInstance(novaLargura, novaAltura, Image.SCALE_SMOOTH);
        return new ImageIcon(imagemRedimensionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFases = new javax.swing.JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(painelFases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(painelFases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelFases;
    // End of variables declaration//GEN-END:variables
}
