/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fase.glasspanes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JLabel;

/**
 *
 * @author klaus
 */
public class ContagemRegressivaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContagemRegressivaPanel
     */
    public ContagemRegressivaPanel() {
        initComponents();
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());
        add(contadorLB, java.awt.BorderLayout.CENTER);
        contadorLB.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contadorLB = new javax.swing.JLabel();

        contadorLB.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        contadorLB.setForeground(new java.awt.Color(255, 0, 0));
        contadorLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorLB.setText("GO!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contadorLB, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contadorLB)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setColor(new Color(0, 0, 51, 150));
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.dispose();
    }

    public JLabel getContadorLB() {
        return contadorLB;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorLB;
    // End of variables declaration//GEN-END:variables
}
